import { Vec2 } from '../math/Vec2';
import { delaunator } from '../math/Delaunator';
import type { LayeredBoardScene } from './BoardPainter';
import { buildCopperGraph, type CopperGraph } from './BoardCopperGraph';

export interface BoardRatsnestLine {
	from: Vec2;
	to: Vec2;
	netId: number;
}

/**
 * Builds a KiCad-style ratsnest from buildCopperGraph's point-level
 * connectivity (paint/BoardCopperGraph.ts): the disconnected components
 * ("islands") of each net are joined by a minimum spanning tree over the
 * islands.
 *
 * The candidate edges for each net's MST are generated by a Delaunay
 * triangulation of the net's anchor points — the same approach and exactly
 * the same candidate-edge set real KiCad uses (pcbnew/ratsnest/ratsnest_data.cpp,
 * its TRIANGULATOR_STATE feeding delaunator_ into kruskalMST) — instead of
 * the previous O(k²·p²) complete-graph MST, which built and compared every
 * node-pair between every pair of islands and became the dominant cost on
 * boards with several densely-meshed islands per net. A Delaunay triangulation
 * is a supergraph of the Euclidean minimum spanning tree, so Kruskal over the
 * (O(n)) triangulation edges yields the true minimum spanning tree between
 * islands while avoiding the quadratic edge candidate blowup.
 *
 * Degenerate nets (fewer than 2 islands, fewer than 3 distinct non-collinear
 * anchor positions) fall back to KiCad's own handling: no MST when fully
 * connected, and a sorted-coordinate chain of candidates when all anchors are
 * collinear (mirroring RN_NET::TRIANGULATOR_STATE::Triangulate's colinear
 * branch).
 *
 * `netFilter`, when given, skips every item whose net isn't in the set —
 * used during a footprint drag to recompute ratsnest for just the nets that
 * moved (see KicadRenderSession's incremental board-rebuild path) instead
 * of the whole board every frame. `graph`, when given, is a precomputed
 * copper graph reused instead of rebuilding one internally. When both a
 * `graph` and a `netFilter` are given, the graph may be the full-board graph
 * — only the filtered nets' lines are produced (see the incremental drag
 * path), so the remaining nets in `graph` are simply not visited.
 */
export function buildBoardRatsnest(scene: LayeredBoardScene, netFilter?: ReadonlySet<number>, graph?: CopperGraph): BoardRatsnestLine[] {
	const { nodes, find } = graph ?? buildCopperGraph(scene, netFilter);

	const result: BoardRatsnestLine[] = [];

	// Group every node index by its net exactly once, so each net is visited
	// with only its own nodes and the netFilter (see below) never pays for
	// non-filtered nets' grouping. When a `netFilter` is present (the
	// incremental drag path), non-filtered nets are skipped during grouping
	// so a full-board graph + a small filter never even walks the unfiltered
	// nets' islands.
	const netToNodeIndices = new Map<number, number[]>();
	for (let index = 0; index < nodes.length; index++) {
		const netId = nodes[index]!.netId;
		if (netId == null || netId <= 0) continue;
		if (netFilter && !netFilter.has(netId)) continue;
		const bucket = netToNodeIndices.get(netId) ?? [];
		bucket.push(index);
		netToNodeIndices.set(netId, bucket);
	}

	for (const [netId, netNodeIndices] of netToNodeIndices) {
		// Connected islands = distinct union-find roots within the net.
		const islandByNode = new Map<number, number>();
		const islands: number[][] = [];
		for (const index of netNodeIndices) {
			const root = find(index);
			let islandIndex = islandByNode.get(root);
			if (islandIndex === undefined) {
				islandIndex = islands.length;
				islands.push([]);
				islandByNode.set(root, islandIndex);
			}
			islands[islandIndex]!.push(index);
		}
		if (islands.length < 2) continue;

		// Collect one anchor (a real node index) per (island, position). Two
		// islands that coincidentally share an exact coordinate each get their
		// own anchor so neither disappears from the MST; they are then bridged
		// by a zero-length edge (see interIslandSamePositionEdges) rather than
		// being collapsed into one triangulation vertex.
		const anchors: { x: number; y: number; island: number }[] = [];
		const positionToAnchor = new Map<string, number>();
		for (let islandIndex = 0; islandIndex < islands.length; islandIndex++) {
			for (const nodeIndex of islands[islandIndex]!) {
				const point = nodes[nodeIndex]!.point;
				const key = `${ islandIndex }\u0000${ point.x }\u0000${ point.y }`;
				if (positionToAnchor.has(key)) continue;
				positionToAnchor.set(key, anchors.length);
				anchors.push({ x: point.x, y: point.y, island: islandIndex });
			}
		}
		if (anchors.length < 2) continue;

		// Zero-length candidates between different islands at one position.
		const interIslandSamePositionEdges: { a: number; b: number }[] = [];
		{
			const byPosition = new Map<string, number[]>();
			for (let i = 0; i < anchors.length; i++) {
				const key = `${ anchors[i]!.x }\u0000${ anchors[i]!.y }`;
				const list = byPosition.get(key) ?? [];
				list.push(i);
				byPosition.set(key, list);
			}
			for (const list of byPosition.values()) {
				if (list.length < 2) continue;
				for (let a = 0; a < list.length; a++) {
					for (let b = a + 1; b < list.length; b++) {
						const ia = list[a]!, ib = list[b]!;
						if (anchors[ia]!.island !== anchors[ib]!.island) {
							interIslandSamePositionEdges.push({ a: ia, b: ib });
						}
					}
				}
			}
		}

		// Delaunay candidate edges over the distinct anchor positions.
		const triangulation = delaunator(anchors.map(p => ({ x: p.x, y: p.y })));
		const delaunayEdges: { a: number; b: number }[] = [];
		if (triangulation.triangles.length > 0) {
			const seen = new Set<string>();
			for (let i = 0; i < triangulation.triangles.length; i += 3) {
				const i0 = triangulation.triangles[i]!;
				const i1 = triangulation.triangles[i + 1]!;
				const i2 = triangulation.triangles[i + 2]!;
				pushUndirectedEdge(seen, delaunayEdges, i0, i1);
				pushUndirectedEdge(seen, delaunayEdges, i1, i2);
				pushUndirectedEdge(seen, delaunayEdges, i2, i0);
			}
		} else if (anchors.length >= 2) {
			// All anchors collinear (or Delaunay could not build) — KiCad
			// chains them along a sorted coordinate. Not strictly required
			// for correctness to sort here (any chain spans the islands), but
			// matching KiCad keeps the resulting airwires in the same order.
			const sorted = anchors.map((anchor, index) => ({ index, ...anchor }));
			sorted.sort((a, b) => a.x - b.x || a.y - b.y);
			for (let i = 0; i < sorted.length - 1; i++) {
				delaunayEdges.push({ a: sorted[i]!.index, b: sorted[i + 1]!.index });
			}
		}

		function pushUndirectedEdge(seen: Set<string>, list: { a: number; b: number }[], a: number, b: number): void {
			const key = a < b ? `${ a }\u0000${ b }` : `${ b }\u0000${ a }`;
			if (seen.has(key)) return;
			seen.add(key);
			list.push({ a, b });
		}

		// Kruskal MST over the islands: sort candidate edges by length, then
		// union islands — exactly RN_NET::kruskalMST's union-find step.
		const allEdges = dedupeEdges([
			...delaunayEdges,
			...interIslandSamePositionEdges,
		]);
		allEdges.sort((e1, e2) => {
			const la = lengthBetween(anchors[e1.a]!, anchors[e1.b]!);
			const lb = lengthBetween(anchors[e2.a]!, anchors[e2.b]!);
			return la - lb;
		});

		const islandParent = islands.map((_, index) => index);
		const islandFind = (index: number): number => {
			while (islandParent[index] !== index) {
				islandParent[index] = islandParent[islandParent[index]!]!;
				index = islandParent[index]!;
			}
			return index;
		};
		const union = (a: number, b: number): void => {
			const ra = islandFind(a), rb = islandFind(b);
			if (ra !== rb) islandParent[rb] = ra;
		};

		let addedForNet = 0;
		for (const edge of allEdges) {
			const aIsland = anchors[edge.a]!.island;
			const bIsland = anchors[edge.b]!.island;
			if (islandFind(aIsland) === islandFind(bIsland)) continue;
			union(aIsland, bIsland);
			result.push({
				from: new Vec2(anchors[edge.a]!.x, anchors[edge.a]!.y),
				to: new Vec2(anchors[edge.b]!.x, anchors[edge.b]!.y),
				netId,
			});
			addedForNet++;
			if (addedForNet >= islands.length - 1) break;
		}
	}

	return result;
}

function lengthBetween(a: { x: number; y: number }, b: { x: number; y: number }): number {
	const dx = a.x - b.x;
	const dy = a.y - b.y;
	return Math.hypot(dx, dy);
}

function dedupeEdges(edges: { a: number; b: number }[]): { a: number; b: number }[] {
	const seen = new Set<string>();
	const result: { a: number; b: number }[] = [];
	for (const edge of edges) {
		const key = edge.a < edge.b
			? `${ edge.a }\u0000${ edge.b }`
			: `${ edge.b }\u0000${ edge.a }`;
		if (seen.has(key)) continue;
		seen.add(key);
		result.push(edge);
	}
	return result;
}
